name: talker_bloc_effects_example
description: A Flutter example of BLoC state and effect logging with Talker.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  bloc_effects: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  talker: ^5.1.20
  talker_bloc_effects:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
